name: hexlet-check

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Hexlet CI
        uses: hexlet/hexlet-ci-action@v5 
